# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0003_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_intro', models.CharField(max_length=20000)),
                ('company_description', models.CharField(max_length=20000)),
                ('company_status', models.BooleanField(default=True)),
            ],
        ),
    ]
