# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0004_companyintro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyintro',
            name='company_description',
        ),
        migrations.AlterField(
            model_name='companyintro',
            name='company_intro',
            field=models.TextField(max_length=20000),
        ),
    ]
