# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0005_auto_20161227_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyintro',
            options={'verbose_name': 'Company Details'},
        ),
    ]
