# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0007_auto_20161227_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.TextField(max_length=20000, verbose_name='Service Detail')),
                ('service_type', models.TextField(max_length=20000, verbose_name='Service Type')),
                ('service_type_detail', models.TextField(max_length=20000, verbose_name='Service Type Detail')),
                ('service_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
