# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.TextField(max_length=20000, verbose_name='Service Detail')),
            ],
            options={
                'verbose_name': 'Service Detail',
                'verbose_name_plural': 'Service Detail',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_detail',
        ),
    ]
