# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0009_auto_20161227_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_detail', models.TextField(max_length=20000, verbose_name='Client Detail')),
            ],
            options={
                'verbose_name': 'Client Detail',
                'verbose_name_plural': 'Client Detail',
            },
        ),
    ]
