# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0010_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_detail', models.TextField(max_length=20000, verbose_name='About Detail')),
                ('about_choose', models.TextField(max_length=20000, verbose_name='Choose Detail')),
                ('about_goal', models.TextField(max_length=20000, verbose_name='Goals')),
            ],
            options={
                'verbose_name': 'About Detail',
                'verbose_name_plural': 'About Detail',
            },
        ),
    ]
