# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0011_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
