# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0012_auto_20170621_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default=1, max_length=300, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(default=True, max_length=200),
        ),
    ]
