# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moirsintl', '0013_auto_20170621_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_intro', models.TextField(max_length=20000, verbose_name='Company Introduction')),
                ('company_about', models.TextField(max_length=20000, verbose_name='Company About')),
                ('company_service_title', models.TextField(max_length=20000, verbose_name='Company Service Title')),
                ('company_service_detail', models.TextField(max_length=20000, verbose_name='Company Service Detail')),
                ('company_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Detail',
                'verbose_name_plural': 'Company Detail',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='CompanyIntro',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
